name: Simple Android Emulator with noVNC

on:
  workflow_dispatch: # Manual trigger

jobs:
  run-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # 1-hour timeout

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install Basic Dependencies
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y x11vnc fluxbox websockify novnc tightvncserver openjdk-17-jdk nodejs npm

      # Step 3: Install Localtunnel
      - name: Install Localtunnel
        run: |
          sudo npm install -g localtunnel

      # Step 4: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Step 5: Set VNC Password
      - name: Set VNC Password
        run: |
          mkdir -p ~/.vnc
          echo "mypassword" > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

      # Step 6: Start Fluxbox (GUI)
      - name: Start Fluxbox
        run: |
          fluxbox &

      # Step 7: Launch Simple Android Emulator
      - name: Launch Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29        # Android 10, lightweight
          target: default      # Basic target
          arch: x86            # Simpler architecture
          profile: pixel_2     # Small device
          ram-size: 1536M      # 1.5GB RAM
          disk-size: 2048M     # 2GB storage
          hw-gpu-mode: off     # No GPU
          script: |
            sleep 60  # Wait for emulator to boot
            echo "Emulator is running!"
            sleep 3000  # Keep running for 50 minutes

      # Step 8: Start VNC Server
      - name: Start VNC Server
        run: |
          x11vnc -forever -rfbauth ~/.vnc/passwd -rfbport 5900 &

      # Step 9: Start noVNC
      - name: Start noVNC
        run: |
          websockify --web=/usr/share/novnc/ 6080 localhost:5900 &

      # Step 10: Show Direct URL
      - name: Show Direct URL
        run: |
          lt --port 6080 > url.txt &
          sleep 15
          cat url.txt
          echo "Password: mypassword"
          echo "Copy the URL above and open it in your browser!"
          sleep 3000  # Keep tunnel alive
