name: Simple Powerful Android Emulator

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Maximum execution time (1 hour)

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Step 4: Start the Android Emulator
      - name: Launch Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33            # Android 13 for modern apps/games
          target: google_apis       # Includes Play Store support
          arch: x86_64              # Best for performance
          profile: pixel_6_pro      # High-end device profile
          ram-size: 4096M           # 4GB RAM
          disk-size: 8192M          # 8GB Storage
          hw-gpu-mode: auto         # Enables GPU acceleration
          disable-spellchecker: true # Slight performance improvement
          script: |
            echo "Waiting for emulator to fully boot..."
            adb wait-for-device shell 'while [[ "$(getprop sys.boot_completed)" != "1" ]]; do sleep 1; done'
            echo "Emulator booted successfully!"

            # Grant necessary permissions
            adb shell pm grant com.example.app android.permission.READ_EXTERNAL_STORAGE
            adb shell pm grant com.example.app android.permission.WRITE_EXTERNAL_STORAGE

            # Install the app (modify path as necessary)
            echo "Installing APK..."
            adb install -r ./app/build/outputs/apk/debug/app-debug.apk

            # Launch the app
            echo "Launching the app..."
            adb shell monkey -p com.example.app -c android.intent.category.LAUNCHER 1

            # Capture logs for debugging
            echo "Capturing logcat output..."
            adb logcat -d > emulator-logcat.log

            # Keep emulator running
            echo "Keeping emulator running for testing..."
            sleep 3000  # ~50 minutes

      # Step 5: Upload APK and Logs for Debugging
      - name: Upload APK and Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: emulator-output
          path: |
            ~/.android/avd/*.ini
            ~/.android/avd/*.log
            ./app/build/outputs/apk/**/*.apk
            emulator-logcat.log

      # Step 6: Cleanup emulator process
      - name: Cleanup Emulator
        if: always()
        run: |
          adb emu kill || true
          echo "Emulator shut down successfully."
