name: Android Emulator with noVNC

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install noVNC and VNC Server
        run: |
          sudo apt update
          sudo apt install -y x11vnc fluxbox websockify novnc
          mkdir -p ~/.vnc
          echo "password" | x11vnc -storepasswd ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

      - name: Launch Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel_6_pro
          ram-size: 4096M
          disk-size: 8192M
          hw-gpu-mode: auto
          disable-spellchecker: true
          script: |
            adb wait-for-device shell 'while [[ "$(getprop sys.boot_completed)" != "1" ]]; do sleep 1; done'
            adb install -r ./app/build/outputs/apk/debug/app-debug.apk
            adb shell monkey -p com.example.app -c android.intent.category.LAUNCHER 1

      - name: Start VNC Server
        run: |
          export DISPLAY=:0
          fluxbox &  # Lightweight GUI
          x11vnc -forever -usepw -rfbport 5900 -display :0 &

      - name: Start noVNC
        run: |
          websockify --web=/usr/share/novnc/ --wrap-mode=ignore 6080 localhost:5900 &

      - name: Show Access Link
        run: |
          echo "✅ noVNC Running!"
          echo "➡️ Open this link to access the emulator: http://localhost:6080/vnc.html?host=localhost&port=6080"
